//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambev.Domain.Resourcers {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ambev.Domain.Resourcers.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Field must be true or false.
        /// </summary>
        public static string BOOLEAN {
            get {
                return ResourceManager.GetString("BOOLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Discount must be between 0 and 1.
        /// </summary>
        public static string DISCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Field cannot be empty.
        /// </summary>
        public static string EMPTY_FIELD {
            get {
                return ResourceManager.GetString("EMPTY_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &apos;Password&apos; field is required.
        /// </summary>
        public static string EMPTY_PASSWORD {
            get {
                return ResourceManager.GetString("EMPTY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid token.
        /// </summary>
        public static string ERROR_AUTHENTICATION {
            get {
                return ResourceManager.GetString("ERROR_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The token has expired or is invalid.
        /// </summary>
        public static string ERROR_DETAIL_AUTHENTICATION {
            get {
                return ResourceManager.GetString("ERROR_DETAIL_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The following fields have errors.
        /// </summary>
        public static string ERROR_DETAIL_DOMAIN {
            get {
                return ResourceManager.GetString("ERROR_DETAIL_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The ID provided in the URL does not match the ID in the request body. ID provided:.
        /// </summary>
        public static string ERROR_DETAIL_ID {
            get {
                return ResourceManager.GetString("ERROR_DETAIL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An unexpected error occurred.
        /// </summary>
        public static string ERROR_DETAIL_INTERNAL_SERVER {
            get {
                return ResourceManager.GetString("ERROR_DETAIL_INTERNAL_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Domain validation error.
        /// </summary>
        public static string ERROR_DOMAIN {
            get {
                return ResourceManager.GetString("ERROR_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid ID.
        /// </summary>
        public static string ERROR_ID {
            get {
                return ResourceManager.GetString("ERROR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Record with the given ID not found. Provided ID:.
        /// </summary>
        public static string ERROR_ID_NEW_EXCEPTION {
            get {
                return ResourceManager.GetString("ERROR_ID_NEW_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Internal Server Error.
        /// </summary>
        public static string ERROR_INTERNAL_SERVER {
            get {
                return ResourceManager.GetString("ERROR_INTERNAL_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter username and password.
        /// </summary>
        public static string ERROR_LOGIN {
            get {
                return ResourceManager.GetString("ERROR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resource not found.
        /// </summary>
        public static string ERROR_RESOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_RESOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AuthenticationError.
        /// </summary>
        public static string ERROR_TYPE_AUTHENTICATION {
            get {
                return ResourceManager.GetString("ERROR_TYPE_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bad Request.
        /// </summary>
        public static string ERROR_TYPE_BAD_REQUEST {
            get {
                return ResourceManager.GetString("ERROR_TYPE_BAD_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DomainValidationError.
        /// </summary>
        public static string ERROR_TYPE_DOMAIN {
            get {
                return ResourceManager.GetString("ERROR_TYPE_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a InternalServerError.
        /// </summary>
        public static string ERROR_TYPE_INTERNAL_SERVER {
            get {
                return ResourceManager.GetString("ERROR_TYPE_INTERNAL_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ResourceNotFound.
        /// </summary>
        public static string ERROR_TYPE_RESOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_TYPE_RESOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter a valid date.
        /// </summary>
        public static string INVALID_DATE {
            get {
                return ResourceManager.GetString("INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The applied discount rule is invalid for the quantity of items in the cart.
        /// </summary>
        public static string INVALID_DISCOUNT_RULE {
            get {
                return ResourceManager.GetString("INVALID_DISCOUNT_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please provide a valid email address.
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid filter type or incompatible filter value.
        /// </summary>
        public static string INVALID_FILTER {
            get {
                return ResourceManager.GetString("INVALID_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter a valid identfier.
        /// </summary>
        public static string INVALID_IDENTIFIED {
            get {
                return ResourceManager.GetString("INVALID_IDENTIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication not validated.
        /// </summary>
        public static string INVALID_LOGIN {
            get {
                return ResourceManager.GetString("INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please provide a valid number.
        /// </summary>
        public static string INVALID_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maximum number of characters is 100.
        /// </summary>
        public static string LENGTH__100 {
            get {
                return ResourceManager.GetString("LENGTH_ 100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maximum number of characters is 15.
        /// </summary>
        public static string LENGTH__15 {
            get {
                return ResourceManager.GetString("LENGTH_ 15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maximum number of characters is 20.
        /// </summary>
        public static string LENGTH__20 {
            get {
                return ResourceManager.GetString("LENGTH_ 20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maximum number of characters is 255.
        /// </summary>
        public static string LENGTH__255 {
            get {
                return ResourceManager.GetString("LENGTH_ 255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maximum number of characters is 50.
        /// </summary>
        public static string LENGTH__50 {
            get {
                return ResourceManager.GetString("LENGTH_ 50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maximum number of characters is 500.
        /// </summary>
        public static string LENGTH__500 {
            get {
                return ResourceManager.GetString("LENGTH_ 500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Field cannot be null.
        /// </summary>
        public static string NULL_FIELD {
            get {
                return ResourceManager.GetString("NULL_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Number must be greater than zero.
        /// </summary>
        public static string NUMBER_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("NUMBER_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must contain at least one lowercase letter.
        /// </summary>
        public static string PASSWORD_LOWERCASE_CHARACTERS {
            get {
                return ResourceManager.GetString("PASSWORD_LOWERCASE_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must be at most 20 characters long.
        /// </summary>
        public static string PASSWORD_MAX_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must be at least 8 characters long.
        /// </summary>
        public static string PASSWORD_MIN_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must contain at least one number.
        /// </summary>
        public static string PASSWORD_NUMBER {
            get {
                return ResourceManager.GetString("PASSWORD_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must contain at least one special character (!, @, #, etc.).
        /// </summary>
        public static string PASSWORD_SPECIAL_CHARACTER {
            get {
                return ResourceManager.GetString("PASSWORD_SPECIAL_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password should contain at least 1 uppercase character..
        /// </summary>
        public static string PASSWORD_UPPERCASE_CHARACTERS {
            get {
                return ResourceManager.GetString("PASSWORD_UPPERCASE_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Purchases of 10 to 20 identical items receive a 20% discount..
        /// </summary>
        public static string QUANTITY_BETWEEN_10_AND_20 {
            get {
                return ResourceManager.GetString("QUANTITY_BETWEEN_10 AND_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You cannot sell more than 20 identical items..
        /// </summary>
        public static string QUANTITY_GREATER_THAN_20 {
            get {
                return ResourceManager.GetString("QUANTITY_GREATER_THAN_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Purchases of 4 or more identical items have a 10% discount.
        /// </summary>
        public static string QUANTITY_GREATER_THAN_4 {
            get {
                return ResourceManager.GetString("QUANTITY_GREATER_THAN_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantity must be greater than zero.
        /// </summary>
        public static string QUANTITY_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("QUANTITY_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Purchases of less than 4 items do not have a discount..
        /// </summary>
        public static string QUANTITY_LESS_THAN_4 {
            get {
                return ResourceManager.GetString("QUANTITY_LESS_THAN_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AuthenticationError.
        /// </summary>
        public static string TYPE_AUTHENTICATION_ERROR {
            get {
                return ResourceManager.GetString("TYPE_AUTHENTICATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ResourceNotFound.
        /// </summary>
        public static string TYPE_NOT_FOND {
            get {
                return ResourceManager.GetString("TYPE_NOT_FOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ValidationError.
        /// </summary>
        public static string TYPE_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("TYPE_VALIDATION_ERROR", resourceCulture);
            }
        }
    }
}
