version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ambev_postgres
    restart: always
    environment:
      POSTGRES_DB: Ambev
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: maypassworD*1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ambev_network

  mongodb:
    image: mongo:latest
    container_name: ambev_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ambev_network

volumes:
  postgres_data:
  mongo_data:

networks:
  ambev_network:

